seed: 42
mixed_precision: fp16
train_csv: /home/mithil/PycharmProjects/lmsys-scoring/data/train_folds.csv
folds:
  - 0
  - 1
  - 2
  - 3
model_name: microsoft/deberta-v3-xsmall
max_len: 1536
batch_size: 8
num_workers: 16
lr: 1e-5
epochs: 3
scheduler: linear
warmup_steps: 0.0
model_dir: /home/mithil/PycharmProjects/lmsys-scoring/models/deberta-v3-xsmall-baseline
num_classes : 3